package pertemuan10;

import static pertemuan10.dbkoneksi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Florentina Minovela
 * Tanggal : 24 Mei 2025
 */
public class fmahasiswa extends javax.swing.JFrame {
    DefaultTableModel DTM = new DefaultTableModel();
    
    
    /**
     * Creates new form fmahasiswa
     */
    public fmahasiswa() throws SQLException {
        initComponents();
        
        tblmhs.setModel(DTM);
        DTM.addColumn("Nama Mahasiswa");
        DTM.addColumn("NIM");
        DTM.addColumn("Jurusan");
        DTM.addColumn("Alamat");
        
        String[] opsiJur = {"Pilih Jurusan", "KAB", "MTI", "DKV", "TIPAR", "BD", "RSK"};
        cbJur.removeAllItems();
        for(int i=0;i<7;i++){
            cbJur.addItem(opsiJur[i]);
        }
        
        lsdtmhs();
        clearform();
        tombol(false);
        cBaru.setEnabled(true);
        cTutup.setEnabled(true);
        fieldAktif(false);
        cbJur.setVisible(false);
    }
    
    private void tombol(boolean opsi){
        cBaru.setEnabled(opsi);
        cUbah.setEnabled(opsi);
        cHapus.setEnabled(opsi);
        cTutup.setEnabled(opsi);
    }
    
    private void fieldAktif(boolean opsi){
        txNama.setEditable(opsi);
        txNIM.setEditable(opsi);
        txJur.setEditable(opsi);
        txAlamat.setEditable(opsi); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txAlamat = new javax.swing.JTextField();
        txNIM = new javax.swing.JTextField();
        txJur = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmhs = new javax.swing.JTable();
        cBaru = new javax.swing.JButton();
        cUbah = new javax.swing.JButton();
        cHapus = new javax.swing.JButton();
        cTutup = new javax.swing.JButton();
        cbJur = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setText("Data Mahasiswa");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel2.setText("Nama Mahasiswa");

        txNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNamaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel3.setText("NIM");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel4.setText("Jurusan");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setText("Alamat");

        txAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txAlamatActionPerformed(evt);
            }
        });

        txNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNIMActionPerformed(evt);
            }
        });

        txJur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txJurActionPerformed(evt);
            }
        });

        tblmhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblmhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmhsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblmhs);

        cBaru.setText("Baru");
        cBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBaruActionPerformed(evt);
            }
        });

        cUbah.setText("Ubah");
        cUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUbahActionPerformed(evt);
            }
        });

        cHapus.setText("Hapus");
        cHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cHapusActionPerformed(evt);
            }
        });

        cTutup.setText("Tutup");
        cTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTutupActionPerformed(evt);
            }
        });

        cbJur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbJur, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cBaru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txJur, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cBaru)
                            .addComponent(cUbah)
                            .addComponent(cHapus)
                            .addComponent(cTutup)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNamaActionPerformed

    private void txNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNIMActionPerformed

    private void txJurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txJurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txJurActionPerformed

    private void txAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txAlamatActionPerformed

    private void cBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBaruActionPerformed
      if(cBaru.getText().equals("Baru")) {
      clearform();
      fieldAktif(true);
      
      txJur.setVisible(false);
      cbJur.setVisible(true);
      cBaru.setText("Simpan");
      cTutup.setText("Batal");
      cUbah.setEnabled(false);
      cHapus.setEnabled(false);
      } else {
          try {
              storeData();
              lsdtmhs();
          } catch (SQLException ex) {
              Logger.getLogger(fmahasiswa.class.getName()).log(Level.SEVERE, null, ex);
          }
        cBaru.setText("Baru");
        cTutup.setText("Tutup");
        clearform();
        fieldAktif(false);
        txJur.setVisible(true);
        cbJur.setVisible(false);
      }
    }//GEN-LAST:event_cBaruActionPerformed

    private void tblmhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmhsMouseClicked
     txNama.setText(tblmhs.getValueAt(tblmhs.getSelectedRow(), 0).toString());
     txNIM.setText(tblmhs.getValueAt(tblmhs.getSelectedRow(), 1).toString());
     txJur.setText(tblmhs.getValueAt(tblmhs.getSelectedRow(), 2).toString());
     txAlamat.setText(tblmhs.getValueAt(tblmhs.getSelectedRow(), 3).toString());
     
     cUbah.setEnabled(true);
     cHapus.setEnabled(true);
    }//GEN-LAST:event_tblmhsMouseClicked

    private void cTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTutupActionPerformed
        if(cTutup.getText().equals("Tutup")) {
           int opsi = JOptionPane.showOptionDialog(this, "Yakin akan menutup aplikasi?", "Konfirmasi tutup aplikasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
           if (opsi==JOptionPane.YES_OPTION){
             System.exit(0);  
           }  
       } else{
           cTutup.setText("Tutup");
           cBaru.setText("Baru");
           cUbah.setText("Ubah");
           cBaru.setEnabled(true);
           cUbah.setEnabled(false);
           cbJur.setVisible(false);
           txJur.setVisible(true);
           fieldAktif(false);
           clearform();
       }
    }//GEN-LAST:event_cTutupActionPerformed

    private void cUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUbahActionPerformed
       if(cUbah.getText().equals("Ubah")) {
           cUbah.setText("Simpan");
           cTutup.setText("Batal");
           cBaru.setEnabled(false);
           cHapus.setEnabled(false);
           fieldAktif(true);
           txNIM.setEditable(false);
           txJur.setVisible(false);
           cbJur.setVisible(true);
           cbJur.setSelectedItem(txJur.getText());
       } else {
           
           try {
               updateData();
               lsdtmhs();
           } catch (SQLException ex) {
               Logger.getLogger(fmahasiswa.class.getName()).log(Level.SEVERE, null, ex);
           }
           
          cUbah.setText("Ubah");
          cTutup.setText("Tutup");
          cBaru.setEnabled(true);
          cUbah.setEnabled(false);
          txJur.setVisible(true);
          cbJur.setVisible(false);
          fieldAktif(false);
          clearform();
       }
    }//GEN-LAST:event_cUbahActionPerformed

    private void cHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cHapusActionPerformed
        int opsi = JOptionPane.showOptionDialog(this, "Yakin akan menghapus data"+txNIM.getText() +" ?", "Konfirmasi Hapus Data", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
           if (opsi==JOptionPane.YES_OPTION){
            try{
                destroyData();
                lsdtmhs();
                clearform();
                cHapus.setEnabled(false);
                cUbah.setEnabled(false);
                
            } catch (SQLException ex){
                System.out.print("Error");
             } 
           }
    }//GEN-LAST:event_cHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new fmahasiswa().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(fmahasiswa.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cBaru;
    private javax.swing.JButton cHapus;
    private javax.swing.JButton cTutup;
    private javax.swing.JButton cUbah;
    private javax.swing.JComboBox<String> cbJur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblmhs;
    private javax.swing.JTextField txAlamat;
    private javax.swing.JTextField txJur;
    private javax.swing.JTextField txNIM;
    private javax.swing.JTextField txNama;
    // End of variables declaration//GEN-END:variables

    private void lsdtmhs() throws SQLException {
      Connection cnn = koneksi();
      
      DTM.getDataVector().removeAllElements();
      DTM.fireTableDataChanged();
      
      if(!cnn.isClosed()){
          PreparedStatement PS = cnn.prepareStatement("SELECT * FROM mhs;");
          ResultSet RS = PS.executeQuery();
        
          while(RS.next()){
            Object[] dtamhs = new Object[4];
              dtamhs [0] = RS.getString("Nama");
              dtamhs [1] = RS.getString("NIM");
              dtamhs [2] = RS.getString("Jurusan");
              dtamhs [3] = RS.getString("Alamat");
              
              DTM.addRow(dtamhs);
          } 
      }
      
    }
    
    private void clearform() {
        txNama.setText("");
        txNIM.setText("");
        txJur.setText("");
        txAlamat.setText("");
    }
    
    private void storeData() throws SQLException {
        Connection cnn = koneksi();
        String nama = txNama.getText();
        String nim = txNIM.getText();
        String jurusan = String.valueOf( cbJur.getSelectedItem() );
        String alamat = txAlamat.getText();
        
        if(!cnn.isClosed()) {
            PreparedStatement PS = cnn.prepareStatement("INSERT INTO mhs(Nama,NIM,Jurusan,Alamat) VALUES(?,?,?,?)");
            PS.setString(1, nama);
            PS.setString(2, nim);
            PS.setString(3, jurusan);
            PS.setString(4, alamat);
            PS.executeUpdate();
            cnn.close();
        }
    }
    
    private void updateData() throws SQLException {
       Connection cnn = koneksi();
       String nama = txNama.getText();
       String nim = txNIM.getText();
       String jurusan = String.valueOf(cbJur.getSelectedItem());
       String alamat = txAlamat.getText();
       
       if(!cnn.isClosed()){
          PreparedStatement PS = cnn.prepareStatement("UPDATE mhs SET Nama=?,Jurusan=?,Alamat=? WHERE NIM=?;");
           PS.setString(1, nama);
           PS.setString(2, jurusan);
           PS.setString(3, alamat);
           PS.setString(4, nim);
           PS.executeUpdate();
           cnn.close(); 
       }
    }
    
    private void destroyData() throws SQLException {
       Connection cnn = koneksi();
       String nim = txNIM.getText();
      
       
       if(!cnn.isClosed()){
          PreparedStatement PS = cnn.prepareStatement("DELETE FROM mhs WHERE NIM=?;");
           PS.setString(1, nim);
           PS.executeUpdate();
           cnn.close(); 
       }
    }
}
